name: Repo - create TOC of README
# description: https://github.com/thlorenz/doctoc

# README.md:
# <!-- START doctoc -->
# <!-- END doctoc -->

run-name: create README table of contents by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "README.md"

permissions:
  contents: write

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: Zheng-Bote/gha-doctoc@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: ./README.md
          FOLDING: false
